language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm

env:
  - DB=mysql

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - mysql -e "CREATE database IF NOT EXISTS simpleRoles" -uroot
  - mysql -e db/schema.sql -uroot
  - mysql -e tests/Seeds/roles.sql -uroot
  - mysql -e tests/Seeds/users.sql -uroot
  - mysql -e tests/Seeds/user_roles.sql -uroot
  - cp config/app_travis.yml config/app.yml

script:
  - cd tests; ant

notifications:
  on_success: never
  on_failure: always
