language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm

env:
  - DB=mysql

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - cd tests; ant

notifications:
  on_success: never
  on_failure: always
