language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
#  - hhvm

env:
  - DB=mysql

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - mysql -e "CREATE database IF NOT EXISTS simpleRoles" -uroot
  - mysql simpleRoles -uroot < db/schema.sql
  - mysql simpleRoles -uroot < tests/Seeds/roles.sql
  - mysql simpleRoles -uroot < tests/Seeds/users.sql
  - mysql simpleRoles -uroot < tests/Seeds/user_roles.sql
  - cp config/app_travis.yml config/app.yml

script:
  - cd tests; ant travis

notifications:
  on_success: never
  on_failure: always
